import { Tasks } from "./../types/task";
export const dummy_tasks: Tasks = {
  results: [
    {
      id: "132442",
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      type: "image",
      price: 200,
      labels: [
        {
          name: "eyes",
          description: "Eyes of the cat",
          attendancy: "R",
          cardinality: "M",
          is_annotation: true,
          children: [
            {
              name: "pupil",
              description: "Pupil inside the eye",
              attendancy: "R",
              cardinality: "S",
              is_annotation: true,
              children: [
                {
                  name: "color",
                  description: "Color of the pupil",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "text",
                },

                {
                  name: "radius",
                  description: "Radius of the pupil in cm",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "number",
                },
              ],
            },
          ],
        },
        {
          name: "number_of_cats",
          description: "How many cats are there is the image",
          attendancy: "R",
          cardinality: "S",
          is_annotation: false,
          label_type: "number",
        },
      ],
    },
    {
      id: "132442",
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      type: "image",
      price: 200,
      labels: [
        {
          name: "eyes",
          description: "Eyes of the cat",
          attendancy: "R",
          cardinality: "M",
          is_annotation: true,
          children: [
            {
              name: "pupil",
              description: "Pupil inside the eye",
              attendancy: "R",
              cardinality: "S",
              is_annotation: true,
              children: [
                {
                  name: "color",
                  description: "Color of the pupil",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "text",
                },

                {
                  name: "radius",
                  description: "Radius of the pupil in cm",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "number",
                },
              ],
            },
          ],
        },
        {
          name: "number_of_cats",
          description: "How many cats are there is the image",
          attendancy: "R",
          cardinality: "S",
          is_annotation: false,
          label_type: "number",
        },
      ],
    },
    {
      id: "132442",
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      type: "image",
      price: 200,
      labels: [
        {
          name: "eyes",
          description: "Eyes of the cat",
          attendancy: "R",
          cardinality: "M",
          is_annotation: true,
          children: [
            {
              name: "pupil",
              description: "Pupil inside the eye",
              attendancy: "R",
              cardinality: "S",
              is_annotation: true,
              children: [
                {
                  name: "color",
                  description: "Color of the pupil",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "text",
                },

                {
                  name: "radius",
                  description: "Radius of the pupil in cm",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "number",
                },
              ],
            },
          ],
        },
        {
          name: "number_of_cats",
          description: "How many cats are there is the image",
          attendancy: "R",
          cardinality: "S",
          is_annotation: false,
          label_type: "number",
        },
      ],
    },
    {
      id: "132442",
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      type: "image",
      price: 200,
      labels: [
        {
          name: "eyes",
          description: "Eyes of the cat",
          attendancy: "R",
          cardinality: "M",
          is_annotation: true,
          children: [
            {
              name: "pupil",
              description: "Pupil inside the eye",
              attendancy: "R",
              cardinality: "S",
              is_annotation: true,
              children: [
                {
                  name: "color",
                  description: "Color of the pupil",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "text",
                  children: [],
                },

                {
                  name: "radius",
                  description: "Radius of the pupil in cm",
                  attendancy: "R",
                  cardinality: "S",
                  is_annotation: false,
                  label_type: "number",
                  children: [],
                },
              ],
            },
          ],
        },
        {
          name: "number_of_cats",
          description: "How many cats are there is the image",
          attendancy: "R",
          cardinality: "S",
          is_annotation: false,
          label_type: "number",
          children: [],
        },
      ],
    },
  ],
};
