import { Tasks } from "./../types/task";
export const dummy_tasks: Tasks = {
  results: [
    {
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      labels: 10,
      type: "image",
      price: 200,
    },
    {
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      labels: 10,
      type: "image",
      price: 200,
    },
    {
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      labels: 10,
      type: "image",
      price: 200,
    },
    {
      title: "Images of Cats for a simple research",
      description: "I need 1000 images of cats for my research project",
      tags: ["Trains", "Animals", "Cats", "Mammals"],
      deadline: new Date(),
      width: 1920,
      height: 1080,
      price_per_datum: 0.15,
      quantity: 1000,
      filled: 100,
      rejected: 200,
      pending: 200,
      extension: "jpg",
      image_type: "rgb",
      complexity: "hard",
      labels: 10,
      type: "image",
      price: 200,
    },
  ],
};
